name: kiwica

services:
  kiwica:
    container_name: ${COMPOSE_PROJECT_NAME}
    entrypoint:
      - /bin/sh
      - /root/generate-rootCA.sh
    hostname: ${COMPOSE_PROJECT_NAME}${FQDN}
    image: kiwica:1.0.0
    restart: ${CONTAINER_RESTART_POLICY:-unless-stopped}
    volumes:
      - type: volume
        source: data
        target: /opt/kiwica
      - type: bind
        source: ${ROOTCA_BIND:-./dummy/rootCA}
        target: /opt/kiwica/rootCA

volumes:
  data:
    name: ${COMPOSE_PROJECT_NAME}_data
